import { services } from "./services";

export const mainMenu = [
  {
    id: 1,
    titlePl: "GŁÓWNA",
    titleRu: "ГЛАВНАЯ",
    titleEn: "",
    titleUa: "",
    url: "/",
  },
  {
    id: 2,
    titlePl: "O NAS",
    titleRu: "О НАС",
    titleEn: "",
    titleUa: "",
    url: "/#about",
  },
  {
    id: 3,
    titlePl: "PORTFOLIO",
    titleRu: "ПОРТФОЛИО",
    titleEn: "",
    titleUa: "",
    url: "/#portfolio",
  },
  {
    id: 4,
    titlePl: "USŁUGI I CENY",
    titleRu: "УСЛУГИ И ЦЕНЫ",
    titleEn: "",
    titleUa: "",
    url: `services/${services[0].url}`,
    addition: [
      {
        id: 1,
        titlePl: "Tworzenie stron internetowych",
        titleRu: "Разработка сайта",
        titleEn: "",
        titleUa: "",
        url: "site-creation",
      },
      {
        id: 2,
        titlePl: "Obsługa strony internetowej",
        titleRu: "Обслуживание сайта",
        titleEn: "",
        titleUa: "",
        url: "website-maintenance",
      },
      {
        id: 3,
        titlePl: "Reklama kontekstowa",
        titleRu: "Контекстная реклама",
        titleEn: "",
        titleUa: "",
        url: "contextual-advertising",
      },
      {
        id: 4,
        titlePl: "SEO-promocja",
        titleRu: "SEO продвижение",
        titleEn: "",
        titleUa: "",
        url: "seo-promotion",
      },
      {
        id: 5,
        titlePl: "SMM-promocja",
        titleRu: "SMM продвижение",
        titleEn: "",
        titleUa: "",
        url: "smm-promotion",
      },
      {
        id: 6,
        titlePl: "Reklama ukierunkowana",
        titleRu: "Таргетированная реклама",
        titleEn: "",
        titleUa: "",
        url: "targeted-advertising",
      },
      {
        id: 7,
        titlePl: "Projektowanie unikalnego designu",
        titleRu: "Разработка уникального дизайна",
        titleEn: "",
        titleUa: "",
        url: "development-of-a-unique-design",
      },
      {
        id: 8,
        titlePl: "Usługa rezerwacji",
        titleRu: "Booking service",
        titleEn: "",
        titleUa: "",
        url: "booking-service",
      },
      {
        id: 9,
        titlePl: "Inne usługi",
        titleRu: "Прочие услуги",
        titleEn: "",
        titleUa: "",
        url: "other-services",
      },
      {
        id: 10,
        titlePl: "Dział funkcjonalny marketingu",
        titleRu: "Функциональный отдел маркетинга",
        titleEn: "",
        titleUa: "",
        url: "functional-marketing-department",
      },
    ],
  },
  {
    id: 5,
    titlePl: "WIADOMOŚCI",
    titleRu: "НОВОСТИ",
    titleEn: "",
    titleUa: "",
    url: "news",
  },
  {
    id: 6,
    titlePl: "KONTAKTY",
    titleRu: "КОНТАКТЫ",
    titleEn: "",
    titleUa: "",
    url: "/#contacts",
  },
];

export const footerMenuJobs = [
  {
    id: 1,
    title: "SMM | Tworzenie stron internetowych | SEO",
  },
  {
    id: 2,
    title: "Target i reklama kontekstowa",
  },
  {
    id: 3,
    title: "Projektowanie | Tworzenie treści",
  },
];
